import Head from "next/head";
import Landing from "../Landing/Landing";
import { useDispatch , useSelector } from "react-redux";
import { getSSR } from "../Redux/StateManager/SSR";
import { GET_ALL_ORDERS } from "../Redux/Order";
import { useEffect } from "react";
import axios from "axios";

export default function Home(props) {
  const userData = useSelector((state) => state.auth.user);
  const loginStatus = useSelector((state) => state.auth.loginStatus)

  const dispatch = useDispatch();
  if(props) {
    dispatch(getSSR(props));
  }

  const { access_token } = userData;
  return (
    <>
      <Head>
        <title>Assignment Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing {...props} />
    </>
  );
}

export async function getServerSideProps(context) {
  const category = await fetch(`https://assignment.servepratham.com/api/customer/Get-All-Category`)
  const cat = await category.json()
  const subjects = await fetch(`https://assignment.servepratham.com/api/customer/SubjectWithCategory`)
  const sub = await subjects.json()
  const company = await fetch(`https://assignment.servepratham.com/api/cms/Company`)
  const cms = await company.json()
  const homeData = await fetch(`https://assignment.servepratham.com/api/home`)
  const home = await homeData.json()

  return {
    props: {
      cat: cat,
      subWithCat: sub,
      company: cms,
      home: home,
    },
  };
}
