import Head from 'next/head'
import Landing from '../Landing/Landing'
import { useDispatch } from 'react-redux'
import { getSSR } from '../Redux/StateManager/SSR'

export default function Home(props) {
  const dispatch = useDispatch();
  dispatch(getSSR(props));
  return (
    <>
      <Head>
        <title>Assignment Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </>
  );
}

export async function getServerSideProps(context) {
  const cat = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/customer/Get-All-Category`,
    {
      headers: {
        Accept: "application/json",
        Authorization: `${process.env.NEXT_PUBLIC_ASSIGNMENT_TOKEN}`,
      },
    }
  );
  const category = await cat.json();

  const sub = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/customer/SubjectWithCategory`,
    {
      headers: {
        Accept: "application/json",
        Authorization: `${process.env.NEXT_PUBLIC_ASSIGNMENT_TOKEN}`,
      },
    }
  );
  const subWithCatagory = await sub.json();

  const company = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/cms`, {
    headers: {
      Accept: "application/json",
      Authorization: `${process.env.NEXT_PUBLIC_ASSIGNMENT_TOKEN}`,
    },
  });
  const cms = await company.json();

  
  return {
    props: {
      cat: category,
      subWithCat: subWithCatagory,
      cms: cms,
    }, // will be passed to the page component as props
  };
  
}
