import Head from 'next/head'
import Store from '../Redux/Store'
import { Provider } from 'react-redux'
import Header from '../Components/Header/Header'
import Landing from '../Landing/Landing'

export default function Home() {
  return (
    <>
      <Head>
        <title>Assignment Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </>
  )
}
